In [15]:
import numpy as np
a  = np.array([6,6,6,5,25])
print(np.mean(a))


9.6


In [26]:
def mod_5(a = np.random.randint(1,10,(5,4))):
    for i in range(4):
        print(a[...,i])
mod_5()

[6 3 3 2 3]
[1 5 6 4 2]
[3 3 9 9 9]
[4 6 3 9 5]


In [ ]:
np.random.seed(1)
def mod_5(a = np.random.randint(1,10,(5,4))):
    for i in range(4):
        print(a[...,i])
def mod_5(a = np.random.randint(1,10,(5,4))):
    for i in range(5):
        print(a[i,...])