In [1]:
#Problem1
import average
print(average.k())

ModuleNotFoundError: No module named 'average'

In [5]:
#Problem2
def div(x,y):
    assert y != 0,"Can’t divide"
    return x/y
div(8,4)

2.0

In [27]:
#Problem3
class MyException(Exception):
    pass
def example_func(my_list: list):
    my_sum = 0
    sum_of_pairs = []
    try:
        if type(my_list) != list:
            raise MyException("Typeeror for my_list .Must be a list")
        for i in range(len(my_list)):
            sum_of_pairs.append(my_list[i] + my_list[i + 1])
        print("sum_of_pairs = ",sum_of_pairs)
    except IndexError as i:
        print(i)
    except Exception as e:
        print(e)
example_func("hjlk")

Typeeror for my_list .Must be a list


In [2]:
#Problem4
def UpperContent(filename):
    try:
        myfile = open(filename, "r")
        for line in myfile:
            print(line.upper)
        myfile.close
    except FileNotFoundError as f:
        print(f)
    except Exxception as e:
        print(e)
UpperContent("ttt.txt")

[Errno 2] No such file or directory: 'ttt.txt'


In [6]:
#Problem5
import numpy as np
a = np.random.randint(1,10,(3,5))
a

array([[8, 5, 1, 9, 9],
       [8, 8, 1, 7, 9],
       [4, 5, 8, 6, 7]])

In [9]:
#Problem6
a = np.zeros(10,dtype = int)
a[5] = 3
a

array([0, 0, 0, 0, 0, 3, 0, 0, 0, 0])

In [11]:
#Problem7
a = np.arange(3,15)
a

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
#Problem8
a = np.array([1, 3, 5, 2, 4, 5])
a = a.reshape(2,3)
a

array([[1, 3, 5],
       [2, 4, 5]])

In [15]:
#Problem9
def div(arr):
    while np.mean(arr) > 5:
        for i in range(len(arr)):
            arr[i] /= 2
    print(arr)
div(np.array([9,10,5,9,6,10,8]))

[4 5 2 4 3 5 4]


In [19]:
#Problem10
def col(a = np.random.randint(1,15,(5,4))):
    for i in range(4):
        print(a[...,i])
def row(a = np.random.randint(1,15,(5,4))):
    for i in range(5):
        print(a[i,...])
col(),row()

[11  2 13  8  1]
[10  5 13 10 11]
[ 7  8  2  1 11]
[ 7  1 14 14  1]
[12  4 13  2]
[10 14 13  3]
[ 4  9 12  3]
[10  7 10  1]
[12  9  6  1]


(None, None)